version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: birdsphere_postgres
    environment:
      POSTGRES_DB: birdsphere
      POSTGRES_USER: birdsphere_user
      POSTGRES_PASSWORD: birdsphere_password_123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: birdsphere_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: